FROM cypress/browsers:chrome65-ff57

# set working directory
RUN mkdir /usr/src/app
WORKDIR /usr/src/app

# install cypress
RUN npm install cypress

RUN npm install @babel/core @babel/preset-env babel-loader webpack
RUN npm i ts-loader @cypress/webpack-preprocessor
RUN npm i typescript

# copy cypress files and folders
COPY cypress /usr/src/app/cypress
COPY cypress.json /usr/src/app/cypress.json

# confirm the cypress install
RUN ./node_modules/.bin/cypress verify