sudo: required
language: node_js
node_js:
  - 10

services:
  - docker
env:
  global:
    - DOCKER_COMPOSE_VERSION=1.25.5

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  - echo "$HEROKU_API_KEY" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com
  # - docker build -t allanzou9833/client-test -f ./client/Dockerfile.dev ./client
before_script:
  - docker-compose up -d build
script:
  # - docker run -e CI=true allanzou9833/client-test npm run test
  - docker-compose run cypress ./node_modules/.bin/cypress run
after_script:
  - docker-compose down
after_success:
  - docker build -t registry.heroku.com/$HEROKU_APP_CLIENT/web ./client
  - docker build -t registry.heroku.com/$HEROKU_APP_SERVER/web ./server
  - docker push registry.heroku.com/$HEROKU_APP_CLIENT/web
  - docker push registry.heroku.com/$HEROKU_APP_SERVER/web
  - heroku container:release web --app $HEROKU_APP_CLIENT
  - heroku container:release web --app $HEROKU_APP_SERVER