sudo: required
language: generic
services:
- docker
before_install:
- docker build -t allanzou9833/client-test -f ./client/Dockerfile.dev ./client
script:
- docker run -e CI=true allanzou9833/client-test npm run test
after_success:
- docker build -t registry.heroku.com/$HEROKU_APP_CLIENT/web ./client
- docker build -t registry.heroku.com/$HEROKU_APP_SERVER/web ./server
- echo "$HEROKU_API_KEY" | docker login -u _ --password-stdin registry.heroku.com
- docker push registry.heroku.com/$HEROKU_APP_CLIENT/web
- docker push registry.heroku.com/$HEROKU_APP_SERVER/web
- heroku container:release web --app $HEROKU_APP_CLIENT
- heroku container:release web --app $HEROKU_APP_SERVER