sudo: required
language: node_js
  - "9"
services:
  - docker
before_install:
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  - echo "$HEROKU_API_KEY" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com
  # - docker build -t allanzou9833/client-test -f ./client/Dockerfile.dev ./client
before_script:
  - docker-compose up -d build
script:
  # - docker run -e CI=true allanzou9833/client-test npm run test
  - docker-compose run cypress ./node_modules/.bin/cypress run
after_script:
  - docker-compose down
after_success:
  - docker build -t registry.heroku.com/$HEROKU_APP_CLIENT/web ./client
  - docker build -t registry.heroku.com/$HEROKU_APP_SERVER/web ./server
  - docker push registry.heroku.com/$HEROKU_APP_CLIENT/web
  - docker push registry.heroku.com/$HEROKU_APP_SERVER/web
  - heroku container:release web --app $HEROKU_APP_CLIENT
  - heroku container:release web --app $HEROKU_APP_SERVER