sudo: required
language: generic
services:
  - docker
before_install:
  - docker build -t allanzou9833/client-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true allanzou9833/client-test npm run test
after_success:
  - (echo "$HEROKU_USER" echo "$HEROKU_CREDENTIALS_PASSWORD") | heroku login
  - docker build -t registry.heroku.com/$HEROKU_APP_CLIENT/web ./client
  - docker build -t registry.heroku.com/$HEROKU_APP_SERVER/web ./server
  - echo $(heroku auth:token) | docker login -u "$HEROKU_USER" --password-stdin registry.heroku.com
  - docker push registry.heroku.com/$HEROKU_APP_CLIENT/web
  - docker push registry.heroku.com/$HEROKU_APP_SERVER/web
  - heroku container:login
  - heroku container:release web --app $HEROKU_APP_CLIENT
  - heroku container:release web --app $HEROKU_APP_SERVER
