sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t allanzou9833/client-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true allanzou9833/client-test npm run test

after_success:
  - docker build -t allanzou9833/td-client ./client
  - docker build -t allanzou9833/td-socketio ./server
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push allanzou9833/td-client
  - docker push allanzou9833/td-socketio