sudo: required
language: generic
services:
- docker
before_install:
- docker build -t allanzou9833/client-test -f ./client/Dockerfile.dev ./client
script:
- docker run -e CI=true allanzou9833/client-test npm run test
after_success:
- docker build -t registry.heroku.com/truth-drink/web ./client
- docker build -t registry.heroku.com/truth-drink-server/web ./server
- echo "$HEROKU_API_KEY" | docker login -u "$HEROKU_USER" --password-stdin registry.heroku.com
- docker push registry.heroku.com/truth-drink/web
- docker push registry.heroku.com/truth-drink-server/web
