version: '3'
services:
  socketio:
    image: allanzou9833/td-test-server
    ports:
      - '8080:3000'
  ui:
    build: 
      context: ./client
      dockerfile: Dockerfile.ci
      # args: 
      #   - CONFIGURATION=ci
    depends_on: 
      - socketio
    ports:
      - '4200:80'
  cypress:
    build: 
      context: ./client
      dockerfile: Dockerfile.cypress
    depends_on: 
      - ui
    network_mode: 'host'