FROM node:alpine
WORKDIR /app
COPY package*.json ./
RUN npm install
RUN npm install -g ts-node
# If you are building your code for production
# RUN npm ci --only=production
COPY . .
EXPOSE 3000
CMD [ "npm", "run", "dev" ]